http://www.votes20.gov.il/nationalresults

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('./results/israel/expb.csv')

In [6]:
df.head()

,שם ישוב,סמל ישוב,מספר קלפי,בזב,מצביעים,פסולים,כשרים,אמת,ג,ודעם,...,ני,נץ,ע,פה,ף,ףץ,קנ,קץ,רק,שס
0,אבו ג'ווייעד (שבט,967,1,425,66,5,61,4,0,49,...,0,0,4,1,0,0,0,0,0,0
1,אבו ג'ווייעד (שבט,967,2,638,145,1,144,16,0,120,...,0,0,2,0,0,1,0,1,0,2
2,אבו ג'ווייעד (שבט,967,3,547,102,1,101,19,0,73,...,0,0,2,0,0,0,0,0,0,0
3,אבו גוש,472,1,705,442,4,438,41,2,359,...,0,0,3,3,0,2,0,0,0,4
4,אבו גוש,472,2,724,458,3,455,23,0,397,...,0,0,8,2,0,0,1,1,0,2

In [8]:
df.to_excel('./results/israel/expb.xlsx')

In [9]:
dfc = pd.read_csv('./results/israel/expc.csv')

In [12]:
dfc.head()

,שם ישוב,סמל ישוב,בזב,מצביעים,פסולים,כשרים,אמת,ג,ודעם,ז,...,ני,נץ,ע,פה,ף,ףץ,קנ,קץ,רק,שס
0,NaN,0,0,234599,1918,232681,41202,6268,7299,49,...,45,50,517,21885,101,153,8472,6758,311,10347
1,אבו ג'ווייעד (שבט,967,1610,313,7,306,39,0,242,0,...,0,0,8,1,0,1,0,1,0,2
2,אבו גוש,472,4178,2539,33,2506,143,4,2114,0,...,0,1,41,14,0,4,2,5,2,35
3,אבו סנאן,473,8363,5798,52,5746,299,3,3802,0,...,1,2,47,41,1,5,11,21,2,213
4,אבו עבדון (שבט),958,119,37,1,36,0,0,35,0,...,0,0,1,0,0,0,0,0,0,0

In [13]:
dfc.to_excel('./results/israel/expc.xlsx')

In [15]:
df.count()

 שם ישוב     10414
סמל ישוב     10414
מספר קלפי    10414
בזב          10414
מצביעים      10414
פסולים       10414
כשרים        10414
אמת          10414
ג            10414
ודעם         10414
ז            10414
זך           10414
זץ           10414
טב           10414
י            10414
יז           10414
יך           10414
יץ           10414
כ            10414
ל            10414
מחל          10414
מרצ          10414
נז           10414
ני           10414
נץ           10414
ע            10414
פה           10414
ף            10414
ףץ           10414
קנ           10414
קץ           10414
רק           10414
שס           10414
dtype: int64